#ifndef CONSTANTS_HPP
# define CONSTANTS_HPP

# define BUFFER_SIZE 	1024
# define PORT			6667
# define TIMEOUT_POLL	1	

#define RPL_WELCOME		"001"
#define RPL_YOURHOST	"002"
#define RPL_CREATED 	"003"
#define RPL_MYINFO		"004"
#define RPL_LUSERME		"255"
#define RPL_ENDOFWHO	"315"
#define RPL_CHANMODEIS	"324"
#define RPL_NOTOPIC		"331"
#define RPL_YESTOPIC	"332"
#define RPL_LISTNAMES	"353"
#define RPL_ENDLISTN	"366"
#define RPL_INVITING	"341"
#define RPL_MOTDSTART	"375"
#define RPL_MOTD		"372"
#define RPL_ENDOFMOTD	"376"

#define ERR_NOSUCHNICK		"401"
#define ERR_NOCHAN			"403"
#define ERR_CANTSENDCHAN	"404"
#define ERR_NORECIPIENT		"411"
#define ERR_NOTEXTTOSEND	"412"
#define ERR_NONICKGIVEN		"431"
#define ERR_NICKNAMEINUSE	"433"
#define ERR_USERNOTINCHAN	"441"
#define ERR_NOTONCHANNEL	"442"
#define ERR_USERONCHANNEL	"443"
#define ERR_NOTREGISTERED	"451"
#define ERR_NOPARAMS		"461"
#define ERR_NOREGISTER		"462"
#define ERR_PASSWDMISMATCH	"464"
#define ERR_KEYSET			"467"
#define	ERR_CANTJOINL		"471"
#define ERR_UNKNOWNMODE		"472"
#define	ERR_CANTJOINI		"473"
#define ERR_CANTJOINK		"475"
#define ERR_COPRIVSNEEDED	"482"

#endif